version: "3"

services:

  postgres:
    container_name: postgres
    image: postgres:alpine
    user: root
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ${POSTGRES_DIR_PATH}:/var/lib/postgresql/data


  server:
    image: nestjs-logger-example
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    command: npm start
    environment:
      NODE_ENV: development
      HOST: "${HOST}"
      PORT: "${PORT}"
      POSTGRES_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}"
      PAPERTRAIL_HOST: "${PAPERTRAIL_HOST}"
      PAPERTRAIL_PORT: "${PAPERTRAIL_PORT}"
    depends_on:
      - postgres
    links:
      - postgres

