version: "3"

services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  server:
    image: nestjs-logger-example
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm start
    environment:
      NODE_ENV: development
      HOST: "0.0.0.0"
      PORT: 3000
      POSTGRES_URL: postgres://postgres:password@postgres/postgres
      PAPERTRAIL_HOST: "${PAPERTRAIL_HOST}"
      PAPERTRAIL_PORT: "${PAPERTRAIL_PORT}"
    depends_on:
      - postgres
    links:
      - postgres

